Roommates.WebUI/Roommates.WebUI/Controllers/HomeController.cs
using System.Web.Mvc;
using Roommates.Common.Consts;
using Roommates.WebUI.Models.ConrolsModels;
using Roommates.WebUI.Models.TicketModels;

namespace Roommates.WebUI.Controllers
{
    public class HomeController : BaseController
    {
        public ActionResult Index()
        {
            //List<TicketModel> allTickets = RoommatesEntities.Tickets.ToList().Select(item => new TicketModel(item)).ToList();
            var searchModel = new TicketsSearchModel()
                {
                    SliderModel = new SliderModel()
                        {
                            PriceMin = 5000,
                            PriceMax = 15000
                        },
                    NeighbourSex = Sex.NotImportant,
                    PersonsCount = PersonCount.NotImportant,
                    Smoking = false,
                    Pets = false,
                    TicketTypes = TicketTypesSearch.NotImportant
                };
            return View(searchModel);
        }
    }
}

Roommates.WebUI/Roommates.WebUI/Controllers/TicketController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using Roommates.Common.Consts;
using Roommates.DataLayer.Model;
using Roommates.WebUI.Models.ConrolsModels;
using Roommates.WebUI.Models.StandartModels;
using Roommates.WebUI.Models.TicketModels;

namespace Roommates.WebUI.Controllers
{
    public class TicketController : BaseController
    {
        /// <summary>
        /// Тестовый метод - берет все тикеты с указанными параметрами и вызывает view, которая рисует табличку с ними
        /// </summary>
        public ActionResult Index()
        {
            JsonResult jsonResult = GetTickets(new TicketsSearchModel
                {
                    LeftUpCorner = new PointDouble(-1000, -1000),
                    RightDownCorner = new PointDouble(1000, 1000),
                    SliderModel = new SliderModel
                        {
                            PriceMin = 0,
                            PriceMax = 100000
                        },
                    Smoking = false,
                    Pets = false,
                    NeighbourSex = Sex.Male,
                    PersonsCount = PersonCount.Few
                });
            List<Ticket> tickets = jsonResult.Data as List<Ticket>;
            return View(tickets);
        }

        /// <summary>
        /// Тестовый метод - добавляем "случайный" тикет в базу, а потом вызываем тестовый метод Index
        /// </summary>
        public ActionResult AddRandomTicket()
        {
            Random rand = new Random(DateTime.Now.Millisecond);
            
            int minPrice = rand.Next(10000);
            AddTicket(new PointDouble(rand.NextDouble(), rand.NextDouble()),
                      new PointDouble(rand.NextDouble(), rand.NextDouble()), minPrice, minPrice + rand.Next(10000),
                      false, false, true, (int) Sex.Male, (int) PersonCount.Few, 1);
            return RedirectToAction("Index");
        }

        public JsonResult GetAllTickets()
        {
            List<TicketModel> tickets = RoommatesEntities.Tickets.Include("Person").ToList().Select(item => new TicketModel(item)).ToList();
            return Json(tickets);
        }

        /// <summary>
        /// Рабочий метод - получает набор тикетов, подходящих под указанные параметры.
        /// Возвращает Json
        /// </summary>
        public JsonResult GetTickets(TicketsSearchModel searchModel)
        {
            Logger.Write(String.Format("Call getTickets whith priceMax: {0}, priceMin: {1}, [{2}, {3}] [{4}, {5}]",
                                       searchModel.SliderModel.PriceMax, searchModel.SliderModel.PriceMin,
                                       searchModel.LeftUpCorner.X, searchModel.LeftUpCorner.Y,
                                       searchModel.RightDownCorner.X, searchModel.RightDownCorner.Y));
            IQueryable<Ticket> queryableTickets = RoommatesEntities.Tickets.Include("Person");
            queryableTickets = queryableTickets.Where(ticket => ticket.PriceMax >= searchModel.SliderModel.PriceMin && ticket.PriceMin <= searchModel.SliderModel.PriceMax);
            queryableTickets = queryableTickets.Where(ticket => (!searchModel.Smoking || ticket.Smoking == searchModel.Smoking) && 
                                                                (!searchModel.Pets || ticket.Pets == searchModel.Pets) &&
                                                                (searchModel.PersonsCount == PersonCount.NotImportant || (int) searchModel.PersonsCount == ticket.PersonsCount));
            queryableTickets =
                queryableTickets.Where(ticket => (searchModel.TicketTypes == TicketTypesSearch.NotImportant ||
                                                 (searchModel.TicketTypes == TicketTypesSearch.Appartment && ticket.WithHouse.HasValue && ticket.WithHouse.Value) ||
                                                 (searchModel.TicketTypes == TicketTypesSearch.Human && ticket.WithHouse.HasValue && !ticket.WithHouse.Value)));
            queryableTickets = queryableTickets.Where(ticket => searchModel.NeighbourSex == Sex.NotImportant || (byte)searchModel.NeighbourSex == ticket.Sex);
            List<Ticket> ticketTables = queryableTickets.ToList();
            ticketTables = ticketTables.Where(ticket => IsTicketInSelect(ticket, searchModel.LeftUpCorner, searchModel.RightDownCorner)).ToList();
            List<TicketModel> ticketModels = ticketTables.Select(q => new TicketModel(q)).ToList();
            return Json(ticketModels);
        }

        /// <summary>
        /// Рабочий метод - добавляет тикет в базу. На данный момент, не добавляет фото.
        /// </summary>
        public void AddTicket(PointDouble leftUpCorner, PointDouble rightDownCorner, int priceMin, int priceMax, bool smoking, bool pets, bool sex, int neighbourSex, int personCount, int personId)
        {
            PointDouble center = new PointDouble((leftUpCorner.X + rightDownCorner.X) / 2, (leftUpCorner.Y + rightDownCorner.Y) / 2);
            leftUpCorner.X /= 2;
            leftUpCorner.Y /= 2;
            rightDownCorner.X /= 2;
            rightDownCorner.Y /= 2;
            double radius = leftUpCorner.GetDistance(rightDownCorner);
            Ticket ticket = new Ticket
                {
                    PersonID = personId,
                    Sex = sex ? (byte)1 : (byte)0,
                    XCoord = center.X,
                    YCoord = center.Y,
                    Radius = radius,
                    Pets = pets,
                    Smoking = smoking,
                    PersonsCount = personCount,
                    NeighbourSex = (byte) neighbourSex,
                    PriceMin = priceMin,
                    PriceMax = priceMax
                };
            RoommatesEntities.Tickets.Add(ticket);
            try
            {
                RoommatesEntities.SaveChanges();
            }
            catch(Exception e)
            {
                Logger.Write(String.Format("{0}; {1}", e.Message, e.InnerException), EventTypes.Error);
            }
        }
        
        #region Private Methods

        /// <summary>
        /// На данный момент смотрим 
        ///     1) лежит ли центр тикета в выделенной области
        ///     2) касаются ли окружности тикета и выделенной области (да, выделенная область во втором случае, рассматривается, как окружность)
        /// </summary>
        private bool IsTicketInSelect(Ticket ticket, PointDouble leftUpCorner, PointDouble rightDownCorner)
        {
            double x = ticket.XCoord;
            double y = ticket.YCoord;
            //check ticket center in selected area
            if (x >= leftUpCorner.X && x <= rightDownCorner.X && y >= leftUpCorner.Y && y <= rightDownCorner.Y)
            {
                return true;
            }
            return false;

            /*leftUpCorner.X /= 2;
            rightDownCorner.X /= 2;
            leftUpCorner.Y /= 2;
            rightDownCorner.Y /= 2;
            PointDouble centerSelected = new PointDouble(leftUpCorner.X + rightDownCorner.X, leftUpCorner.Y + rightDownCorner.Y);
            double radiusSelected = leftUpCorner.GetDistance(rightDownCorner);
            double fullRadius = radiusSelected + ticket.Radius;
            return (centerSelected.GetDistance(new PointDouble(x, y)) < fullRadius);*/
        }

        #endregion
    }
}

Roommates.WebUI/Roommates.WebUI/Views/Home/Index.cshtml
@using Roommates.WebUI.HtmlExtensions
@model Roommates.WebUI.Models.TicketModels.TicketsSearchModel

@{
    ViewBag.Title = "Поиск";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section Headers
{
    <script src="@Url.Content("~/Scripts/ymap.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/ticketJs.js")" type="text/javascript"></script>
}

<div class="container" id="cnt">
    <div class="container-fluid" id="search">
        <div class="well withoutMarginBottom">
            @using (Html.BeginForm("GetTickets", "Ticket", FormMethod.Get, new {style = "margin-bottom: 10px;"}))
            {
                <div class="row-fluid">
                    <div class="span9">
                        @Html.SliderFor(m=>m.SliderModel)
                    </div>
                    <div class="span3">
                        <div class="search-element">
                            <b>Дополнительные опции</b>
                        </div>
                        <div class="dropdown">
                            <a class="btn dropdown-toggle btn-block" data-toggle="dropdown" href="#">
                                Показать
                                <span class="caret"></span>
                            </a>
                            <div class="dropdown-menu" style="width: 100%; padding: 0; padding-bottom: 0; z-index: 15">
                                <div class="" style="padding: 15px;">
                                    <div class="control-group">
                                        @Html.LabelFor(m => m.TicketTypes, new Dictionary<string, object> { { "class", "control-label" } })
                                        <div class="controls">
                                            @Html.RadioButtonForEnum(m => m.TicketTypes)
                                        </div>
                                    </div>
                                    <hr />
                                    <div class="control-group">
                                        @Html.LabelFor(m => m.NeighbourSex, new Dictionary<string, object> { { "class", "control-label" } })
                                        <div class="controls">
                                            @Html.RadioButtonForEnum(m => m.NeighbourSex)
                                        </div>
                                    </div>
                                    <hr />
                                    <div class="control-group">
                                        @Html.LabelFor(m => m.PersonsCount, new Dictionary<string, object> { { "class", "control-label" } })
                                        <div class="controls">
                                            @Html.RadioButtonForEnum(m => m.PersonsCount)
                                        </div>
                                    </div>
                                    <hr />
                                    <div class="control-group">
                                        <label class="control-label">
                                            Кроме того
                                        </label>
                                        <div class="controls">
                                            <label class="checkbox" for="@Html.IdFor(m => m.Smoking)">
                                                @Html.CheckBoxFor(m => m.Smoking)
                                                @Html.DisplayNameFor(m => m.Smoking)
                                            </label>
                                            <label class="checkbox" for="@Html.IdFor(m => m.Pets)">
                                                @Html.CheckBoxFor(m => m.Pets)
                                                @Html.DisplayNameFor(m => m.Pets)
                                            </label>
                                        </div>
                                    </div>
                                    <hr/>
                                    <div class="pointer center"> 
                                        <b>Скрыть</b>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                @Html.HiddenFor(m=>m.LeftUpCorner.X)
                @Html.HiddenFor(m=>m.LeftUpCorner.Y)
                @Html.HiddenFor(m=>m.RightDownCorner.X)
                @Html.HiddenFor(m=>m.RightDownCorner.Y)
            }
        </div>
    </div>

    <div class="container" id="mapContainer">
        <div class="well">
            <div class="absoluteElement">
                <div class="btn-group">
                    <a href="javascript: showMap()" class="btn active" id="mapLink">Карта</a>
                    <a href="javascript: showList()" class="btn" id="listLink">Список</a>
                </div>
            </div> 
            <div id="map">
                
            </div>
            <div id="ticketList" >
                <table class="table table-striped hide">
                    <thead>
                        
                    </thead>
                    <tbody>
                        
                    </tbody>
                </table>
                <div class="hide">
                    Заявок, удовлетворяющих данным критериям, не найдно.
                </div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript" charset="utf-8">
    var yandexmap = new YandexMap(initMap);
    var currentTickets;

    $('.dropdown-menu input, .dropdown-menu label').click(function (e) {
        e.stopPropagation();
    });

    $(document).ready(function() {
        $("form :input").change($.debounce(888, getTickets));
        $("#ticketList").hide();
    });
    
    function showTickets() {
        var data = currentTickets;
        var cntObjects = data.length;
        $("#ticketList tbody").html('');
        if (cntObjects == 0) {
            $("#ticketList div").show();
            $("#ticketList table").hide();
            return;
        }
        $("#ticketList table").show();
        $("#ticketList div").hide();
        yandexmap.initCluster();
        for (var j = 0; j < cntObjects; j++) {
            var ticket = data[j];
            addToList(ticket);
            var i = j;
            yandexmap.DecodeGeoObject([ticket.XCoord, ticket.YCoord], i, function (name, index) {
                $("." + GetAddressClass(data[index].ID)).html(name);
                if (index == cntObjects - 1) {
                    for (var j = 0; j < cntObjects; j++) {
                        addToMap(data[j]);
                    }
                }
            });
            //vkRequest();
        }
        
        yandexmap.drawCluster();
    }
    
    function addToMap(ticket) {
        var ticketJs = new TicketJs(ticket);
        var ticketHeader = "";
        var ticketTemplate = $("#" + ticket.ID).clone();
        $(ticketTemplate).find(".withMinHeigth").removeClass("withMinHeight");
        $(ticketTemplate).find(".maxWidth180").removeClass("maxWidth180");
        $(ticketTemplate).find(".maxWidth130").removeClass("maxWidth130");
        var ticketBody = "<div style='height: 255px;width:300px' class = 'vk_info_" + ticket.VkID + "' id='balloon" + ticket.ID + "'>" + ticketTemplate.html() + "</div>";
        var ticketFooter = "";
        var content = {
            header: ticketHeader,
            body: ticketBody,
            footer: ticketFooter
        };


        var placemark = yandexmap.addPlacemark([ticket.XCoord, ticket.YCoord], content, ticket.ID);

        if (placemark != null) {
            placemark.events.add('balloonopen', function() {
                fillBlock($("#balloon" + ticket.ID));
            });
        }
    }
    
    function GetAddressClass(ticketId) {
        return "addressId" + ticketId;
    }

    function addToList(ticket) {
    	var ticketJs = new TicketJs(ticket);
        var ticketType = ticket.TicketTypes == 0 ? "Ищу квартиру" : "Сдаю квартиру";
        var addressId = GetAddressClass(ticket.ID);
        var ticketPrice = ticket.SliderPrice.PriceMin;
        if (ticket.TicketTypes == 0) {
            ticketPrice = "от " + ticket.SliderPrice.PriceMin + " до " + ticket.SliderPrice.PriceMax;
        }
        var negative = "";
        if (ticket.Smoking) {
            negative = '<img class="listInfoIcon" src="@Url.Content("~/Content/images/nosmoking.png")" rel="tooltip" title="Негативно отношусь к курению"/> ';
        }
        if (ticket.Pets) {
            negative += '<img class="listInfoIcon" src="@Url.Content("~/Content/images/nopets.png")" rel="tooltip" title="Негативно отношусь к домашним животным"/>';
        }

        var details = ticket.Details == null ? "-" : ticket.Details;

        var ticketData =
            '<tr class="vk_info_' + ticket.VkID + '">' +
            '<td>' +
                "<div id=" + ticket.ID  + ">" +
                '<div class="listInfo withMinHeight">' +
                    ticketJs.getPhotoInLink("medium") +
                '</div>' +

                '<div class="listInfo maxWidth130 withMinHeight">' +
                    ticketJs.getNameInLink() +
                    '<div>Пол: <span class="vk_sex"></span></div>' +
                    '<div class="vk_bdate"></div>' +
                '</div>' +

                '<div class="listInfo maxWidth180 withMinHeight">' +
                    '<label>' + ticketType + '</label>' +
                    '<p>' + ticketPrice + "</p>" +
                    '<p><i class="icon-home"/> ' +
                    '<span class="' + addressId + '"\></p>' +
                    ((negative == "") ? "" : "<p>" + negative + "</p>") +
                "</div>" +
                "</div>" +
                '<div class="listInfo">' +
                    '<p>Дополнительная информация:</p>' +
                    '<p class="detailsInfo">' + details + '</p>' +
                '</div>' +
            "</td></tr>";

        $("#ticketList tbody").append(ticketData);
        $("[rel='tooltip']").tooltip();
    }

    function initMap() {
        yandexmap.onDrug(getTicketsOnDrag);
        getTickets();
    }
    
    function getTickets() {
        getTicketsCommon(yandexmap.clear);
    }
    
    function getTicketsCommon(clearFunction) {
        var coords = yandexmap.getFrameCoords();

        $("#@Html.IdFor(m => m.LeftUpCorner.X)").val(coords[0][0].toString().replace('.', ','));
                $("#@Html.IdFor(m => m.LeftUpCorner.Y)").val(coords[0][1].toString().replace('.', ','));

        $("#@Html.IdFor(m => m.RightDownCorner.X)").val(coords[1][0].toString().replace('.', ','));
        $("#@Html.IdFor(m => m.RightDownCorner.Y)").val(coords[1][1].toString().replace('.', ','));

        $("form").ajaxSubmit({
            url: '@Url.Action("GetTickets", "Ticket")',
            type: 'post',
            async: false,
            success: function (data) {
                clearFunction();
                currentTickets = data;
                showTickets();
            }
        });
    }
    
    function getTicketsOnDrag() {
        getTicketsCommon(yandexmap.clearOutsideTicket);
    }
    
    $(window).resize(function() {
        remap();
    });

    function remap(){
        var h = $(window).height() - $("#map").position().top - 50;
        $("#map").height(Math.max(h,300));
    }
    
    function showList() {
        vkRequest();
        $("#map").hide();
        $("#ticketList").show();
        $("#listLink").addClass("active");
        $("#mapLink").removeClass("active");
    }
    function showMap() {
        $("#ticketList").hide();
        $("#map").show();
        $("#mapLink").addClass("active");
        $("#listLink").removeClass("active");
    }
    
    $(window).resize();
</script>